# Generated by Django 5.1.2 on 2026-09-22 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("grading", "0001_initial"),
        ("students", "0002_permitir_seccion_academica_y_taller_a_la_vez"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobado", "Aprobado"),
                            ("publicado", "Publicado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de aprobación"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de publicación"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprobado por",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="students.enrollment",
                        verbose_name="inscripción",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generado por",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_cards",
                        to="catalog.gradingunit",
                        verbose_name="unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "boletín",
                "verbose_name_plural": "boletines",
                "ordering": ["-unit", "enrollment"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "unit"), name="boletin_unico_por_unidad"
                    )
                ],
            },
        ),
    ]
