# Generated by Django 5.2.17 on 2026-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_reportcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradechangerequest',
            name='resolution_note',
            field=models.TextField(blank=True, help_text='Por qué Dirección la aprobó o rechazó; el docente lo ve en su bandeja.', verbose_name='motivo de la decisión'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='contenido',
            field=models.JSONField(blank=True, help_text='Las notas tal como estaban al aprobar el boletín. Es lo que se publica y se descarga: un documento oficial no cambia porque después se corrija una nota.', null=True, verbose_name='contenido aprobado'),
        ),
    ]
