# Generated by Django 5.2.17 on 2026-09-23 16:07

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="justification",
            name="supporting_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="justificaciones/%Y/%m/",
                validators=[apps.core.validators.validar_documento_de_respaldo],
                verbose_name="documento de respaldo",
            ),
        ),
    ]
