# Generated by Django 5.2.17 on 2026-10-08 02:36

from django.db import migrations, models


def tarde_a_presente(apps, schema_editor):
    """Se eliminó el estado "tarde": lo ya registrado cuenta como presente."""
    Attendance = apps.get_model("attendance", "Attendance")
    Attendance.objects.filter(status="tarde").update(status="presente")


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_justification_supporting_document"),
    ]

    operations = [
        migrations.RunPython(tarde_a_presente, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("presente", "Presente"),
                    ("ausente", "Ausente"),
                    ("justificado", "Justificado"),
                ],
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
