# Generated by Django 5.1.2 on 2026-09-23 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("students", "0002_permitir_seccion_academica_y_taller_a_la_vez"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "audience",
                    models.CharField(
                        choices=[("todos", "Todos"), ("seccion", "Una sección")],
                        max_length=20,
                        verbose_name="destinatario",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de publicación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publicado por",
                    ),
                ),
                (
                    "target_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="catalog.section",
                        verbose_name="sección destinataria",
                    ),
                ),
            ],
            options={
                "verbose_name": "aviso",
                "verbose_name_plural": "avisos",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ConductReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField(verbose_name="fecha")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("grave", "Grave"),
                            ("muy_grave", "Muy grave"),
                        ],
                        max_length=20,
                        verbose_name="tipo de falta",
                    ),
                ),
                (
                    "incident_description",
                    models.TextField(verbose_name="hechos ocurridos"),
                ),
                (
                    "immediate_actions",
                    models.TextField(verbose_name="medidas inmediatas tomadas"),
                ),
                (
                    "other_violation_detail",
                    models.TextField(
                        blank=True, verbose_name="otra falta no especificada"
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(
                        choices=[
                            ("llamado_verbal", "Llamado verbal"),
                            ("amonestacion_escrita", "Amonestación escrita"),
                            ("comunicacion_familia", "Comunicación a la familia"),
                            (
                                "suspension_extracurricular",
                                "Suspensión de actividades extracurriculares",
                            ),
                            ("servicio_comunitario", "Servicio comunitario"),
                            ("suspension_clases", "Suspensión de clases"),
                            ("evaluacion_expulsion", "Evaluación para expulsión"),
                            ("otra", "Otra"),
                        ],
                        max_length=30,
                        verbose_name="tipo de sanción",
                    ),
                ),
                (
                    "sanction_detail",
                    models.TextField(blank=True, verbose_name="detalle de la sanción"),
                ),
                (
                    "commitments",
                    models.TextField(verbose_name="compromisos establecidos"),
                ),
                (
                    "direction_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conduct_reports_as_direction",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="miembro de dirección",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conduct_reports",
                        to="students.enrollment",
                        verbose_name="inscripción",
                    ),
                ),
                (
                    "guide_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conduct_reports_as_guide",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="maestro guía",
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de conducta",
                "verbose_name_plural": "reportes de conducta",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="ConductReportArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.conductrulearticle",
                    ),
                ),
                (
                    "conduct_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_articles",
                        to="communication.conductreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "artículo incumplido",
                "verbose_name_plural": "artículos incumplidos",
            },
        ),
        migrations.AddField(
            model_name="conductreport",
            name="articles",
            field=models.ManyToManyField(
                related_name="conduct_reports",
                through="communication.ConductReportArticle",
                to="catalog.conductrulearticle",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(blank=True, max_length=150, verbose_name="asunto"),
                ),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("leido", "Leído"),
                            ("respondido", "Respondido"),
                        ],
                        default="enviado",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "original_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replies",
                        to="communication.message",
                        verbose_name="mensaje original",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="catalog.section",
                        verbose_name="sección",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje de buzón",
                "verbose_name_plural": "mensajes de buzón",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="conductreportarticle",
            constraint=models.UniqueConstraint(
                fields=("conduct_report", "article"), name="articulo_unico_por_reporte"
            ),
        ),
    ]
