# Generated by Django 5.1.2 on 2026-09-21 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "screen_viewed",
                    models.CharField(
                        max_length=255, verbose_name="pantalla consultada"
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accesos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de acceso",
                "verbose_name_plural": "registro de accesos",
                "indexes": [
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="core_access_user_id_e3d060_idx",
                    ),
                    models.Index(
                        fields=["accessed_at"], name="core_access_accesse_fcac8f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "entity_name",
                    models.CharField(max_length=100, verbose_name="entidad afectada"),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(verbose_name="id de la entidad"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("crear", "Crear"),
                            ("actualizar", "Actualizar"),
                            ("eliminar", "Eliminar"),
                        ],
                        max_length=20,
                        verbose_name="acción",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="valor anterior"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="valor nuevo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cambios_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de bitácora",
                "verbose_name_plural": "bitácora de cambios",
                "indexes": [
                    models.Index(
                        fields=["entity_name", "entity_id", "created_at"],
                        name="core_auditl_entity__b1ec5b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_auditl_user_id_413764_idx",
                    ),
                ],
            },
        ),
    ]
