# Generated by Django 5.1.2 on 2026-09-22 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                (
                    "counts_as_short_quiz",
                    models.BooleanField(
                        default=False,
                        help_text="RN-04: se usa para exigir el mínimo de 4 pruebas cortas por unidad.",
                        verbose_name="cuenta como prueba corta",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de actividad evaluativa",
                "verbose_name_plural": "tipos de actividad evaluativa",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "type",
                    models.CharField(
                        choices=[("academico", "Académico"), ("taller", "Taller")],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                (
                    "template_key",
                    models.CharField(
                        help_text="Identifica la plantilla de PDF de este documento (se conecta en la Fase 9).",
                        max_length=80,
                        verbose_name="plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de documento",
                "verbose_name_plural": "tipos de documento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JustificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, verbose_name="requiere documento de respaldo"
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de justificación",
                "verbose_name_plural": "tipos de justificación",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="nombre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "beca",
                "verbose_name_plural": "becas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField(unique=True, verbose_name="año")),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                ("end_date", models.DateField(verbose_name="fecha de cierre")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("activo", "Activo"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="planificado",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "ciclo escolar",
                "verbose_name_plural": "ciclos escolares",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="ConductRuleArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chapter", models.CharField(max_length=120, verbose_name="capítulo")),
                ("code", models.CharField(max_length=20, verbose_name="código")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "artículo del código de convivencia",
                "verbose_name_plural": "artículos del código de convivencia",
                "ordering": ["chapter", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chapter", "code", "description"),
                        name="articulo_unico_por_descripcion",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.CharField(max_length=60, verbose_name="grado")),
                (
                    "letter",
                    models.CharField(blank=True, max_length=5, verbose_name="letra"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("academica", "Académica"), ("taller", "Taller")],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="catalog.schoolcycle",
                        verbose_name="ciclo escolar",
                    ),
                ),
                (
                    "homeroom_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secciones_a_cargo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="maestro guía",
                    ),
                ),
            ],
            options={
                "verbose_name": "sección",
                "verbose_name_plural": "secciones",
                "ordering": ["cycle", "grade", "letter"],
            },
        ),
        migrations.CreateModel(
            name="GradingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField(verbose_name="número")),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                ("end_date", models.DateField(verbose_name="fecha de cierre")),
                (
                    "grades_due_date",
                    models.DateField(verbose_name="fecha de entrega de notas"),
                ),
                (
                    "report_card_enabled_date",
                    models.DateField(verbose_name="fecha de habilitación del boletín"),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="catalog.schoolcycle",
                        verbose_name="ciclo escolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad",
                "verbose_name_plural": "unidades",
                "ordering": ["cycle", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cycle", "number"), name="unidad_unica_por_ciclo"
                    )
                ],
            },
        ),
    ]
