# Generated by Django 5.1.2 on 2026-09-22 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("students", "0002_permitir_seccion_academica_y_taller_a_la_vez"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification_code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="código de verificación",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documentos_emitidos/", verbose_name="archivo"
                    ),
                ),
                (
                    "custom_text",
                    models.TextField(
                        blank=True,
                        help_text="Solo se usa en cartas membretadas; las constancias tienen redacción fija.",
                        verbose_name="texto libre",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de emisión"
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="catalog.documenttype",
                        verbose_name="tipo de documento",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_documents",
                        to="students.enrollment",
                        verbose_name="inscripción",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="emitido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento emitido",
                "verbose_name_plural": "documentos emitidos",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["verification_code"],
                        name="documents_i_verific_1f31da_idx",
                    )
                ],
            },
        ),
    ]
