# Generated by Django 5.1.2 on 2026-09-22 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="nombre completo"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "messaging_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="número de mensajería"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, max_length=100, verbose_name="oficio"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "encargado",
                "verbose_name_plural": "encargados",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "internal_code",
                    models.CharField(
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="código interno",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="apellidos"),
                ),
                ("birth_date", models.DateField(verbose_name="fecha de nacimiento")),
                ("address", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "previous_institution",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="institución anterior"
                    ),
                ),
                (
                    "health_notes",
                    models.TextField(blank=True, verbose_name="datos de salud"),
                ),
                (
                    "socioeconomic_notes",
                    models.TextField(blank=True, verbose_name="datos socioeconómicos"),
                ),
            ],
            options={
                "verbose_name": "estudiante",
                "verbose_name_plural": "estudiantes",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["internal_code"], name="students_st_interna_935e8c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GuardianStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(max_length=60, verbose_name="parentesco"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="encargado principal"
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_links",
                        to="students.guardian",
                        verbose_name="encargado",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_links",
                        to="students.student",
                        verbose_name="estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo encargado-estudiante",
                "verbose_name_plural": "vínculos encargado-estudiante",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guardian", "student"), name="vinculo_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("retirado", "Retirado"),
                            ("graduado", "Graduado"),
                            ("trasladado", "Trasladado"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                ("enrolled_at", models.DateField(verbose_name="fecha de inscripción")),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="catalog.schoolcycle",
                        verbose_name="ciclo escolar",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="catalog.scholarship",
                        verbose_name="beca",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="catalog.section",
                        verbose_name="sección",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="students.student",
                        verbose_name="estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "ordering": ["-cycle", "student"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "cycle"), name="inscripcion_unica_por_ciclo"
                    )
                ],
            },
        ),
    ]
