# Generated by Django 5.1.2 on 2026-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="inscripcion_unica_por_ciclo",
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "cycle", "section"),
                name="inscripcion_unica_por_seccion",
            ),
        ),
    ]
