# Generated by Django 5.1.2 on 2026-09-22 15:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_permitir_seccion_academica_y_taller_a_la_vez"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(
                        help_text="1 a 12.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="mes",
                    ),
                ),
                ("period_year", models.PositiveIntegerField(verbose_name="año")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="monto",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="fecha de pago")),
                (
                    "receipt_number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="número de recibo"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.enrollment",
                        verbose_name="inscripción",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
                "ordering": ["-period_year", "-period_month"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_month__gte", 1), ("period_month__lte", 12)
                        ),
                        name="mes_entre_1_y_12",
                    ),
                    models.UniqueConstraint(
                        fields=("enrollment", "period_year", "period_month"),
                        name="pago_unico_por_mes",
                    ),
                ],
            },
        ),
    ]
