# Generated by Django 5.1.2 on 2026-09-22 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("institucional", "Institucional"),
                            ("asignacion_docente", "Asignación docente"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                ("event_date", models.DateField(verbose_name="fecha")),
                ("start_time", models.TimeField(verbose_name="hora de inicio")),
                ("end_time", models.TimeField(verbose_name="hora de fin")),
                ("materials", models.TextField(blank=True, verbose_name="materiales")),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="scheduling.teacherassignment",
                        verbose_name="asignación docente",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events_published",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="publicado por",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calendar_events",
                        to="catalog.section",
                        verbose_name="sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de calendario",
                "verbose_name_plural": "eventos de calendario",
                "ordering": ["event_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                        ],
                        max_length=20,
                        verbose_name="día",
                    ),
                ),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(verbose_name="período"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_blocks",
                        to="scheduling.teacherassignment",
                        verbose_name="asignación docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloque de horario",
                "verbose_name_plural": "bloques de horario",
                "ordering": ["day_of_week", "period_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "day_of_week", "period_number"),
                        name="bloque_unico_por_asignacion",
                    )
                ],
            },
        ),
    ]
